name: Hikvision Doorbell Fork
description: Lean fork with unlock/ring/call MQTT events
version: '3.0.49'
slug: hikvision_doorbell
url: https://github.com/pergolafabio/Hikvision-Addons/tree/main/doorbell
arch:
- amd64
- aarch64
stage: stable
startup: application
boot: auto
stdin: true
